### ISSUE TITLE
Increase the width or height of the bookmark bar

### ISSUE THREAD

**Issue by readmynameplease** [jesuscc1993/gbf-bookmarker#1]
Hi, Just wondering if it's possible to add such an option to increase the height and width of the bars? because I'm having a hard time clicking on the link without accidentally going out of the selections.

thanks love your work

**Comment by jesuscc1993** [comment]
Just updated the extension to support styles customization. Open your options and paste this in the styles box:
```
body .option {
	padding: 6px 6px; /* default: 4px 6px */
}
```
Then press apply styles.

You can change the first 6 to whatever value you want and reapply the styles to see the updated preview. Ping me if you need further help or close the ticket otherwise.

**Comment by readmynameplease** [comment]
Thanks a lot!
